apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: rate-limit-by-app
  namespace: ai-gateway-demo
plugin: rate-limiting
config:
  minute: 60
  hour: 2000
  limit_by: header
  header_name: X-Application-Id
  policy: local
  fault_tolerant: true
  hide_client_headers: false
